language: node_js

node_js:
  - 13.1.0

branches:
  only:
    - develop

script:
  - export folder=$(pwd)
  - mkdir ../tmp && cd ../tmp
  - npm install hexo-cli -g
  - hexo init blog && cd blog
  - rm -rf source \
    && rm -rf themes \
    && rm -rf $folder\node_modules
  - mv -f $folder/* .
  - npm install \
    && npm install hexo-helper-live2d --save \
    && npm install live2d-widget-model-koharu --save \
    && npm install hexo-renderer-pug --save
  - hexo g
  - rm -f .travis.yml
  - mv master.yml ./public/.travis.yml && mv dockerfile ./ && cd public

after_success:
  - git checkout -b gh
  - git config --local user.name "${U_NAME}"
  - git config --local user.email "${U_EMAIL}"
  - git add .
  - git commit -m ":construction_worker:- Build & Deploy by Lee"
  - git push --force "https://${Travis_Token}@${GIT_REF}" gh:master