sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t blog .
        - docker tag blog $DOCKER_USERNAME/hexo
        - docker push $DOCKER_USERNAME/hexo